fix: base64 encode large arrays
near/near-sdk-as pull request #444
Opened 2021-03-06 20:45 UTC by petersalomonsen

this fixes encoding of Uint8Arrays larger than approx one kb. without this fix I get the error:

```
{
  "ActionError": {
    "index": 0,
    "kind": {
      "FunctionCallError": {
        "HostError": "GasExceeded"
      }
    }
  }
}```

as can be found here.

https://explorer.testnet.near.org/transactions/7DRNWgsza9tRxU3QeYbkjpEoQLZouKfmJxirbk9QuBXL

2021-03-08 22:27 UTC, willemneal commented
Great thanks!

2021-03-09 20:24 UTC, petersalomonsen commented
Not sure what’s going on with the tests though. Seeing it’s failing in master too.

2021-03-09 21:04 UTC, willemneal commented on sdk-core/assembly/base64.ts
> +const PADCHAR = "=";
```suggestion
// @ts-ignore: decorator
@lazy
const PADCHAR = "=";
```

2021-03-09 21:04 UTC, willemneal commented on sdk-core/assembly/base64.ts
> +const ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
```suggestion
// @ts-ignore: decorator
@lazy
const ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
```

2021-03-09 21:05 UTC, willemneal commented on sdk-core/assembly/base64.ts
> +const ALPHAVALUES = new Uint8Array(128);
```suggestion
// @ts-ignore: decorator
@lazy
const ALPHAVALUES = new Uint8Array(128);
```

2021-03-09 21:07 UTC, willemneal requested changes
Thanks for looking into this! There is a separate base64 library that we created, but never moved toward so perhaps this work could also help there.

Currently this fails a test that checks that compiling an empty file produces and empty binary.  This is because we want to make sure that things like unused globals don't end up in the binary, which is why we used the `@lazy` decorator.  Accepting my suggested changes should make them pass.

2021-03-09 21:17 UTC, petersalomonsen commented
yeah ok. I've accepted your changes, makes sense, and still works with my contract :) 

should I rebase+squash too, or will you do it when merging?

2021-03-11 16:38 UTC, willemneal approved these changes

2021-03-11 16:38 UTC, merged